export const WORLD_CONFIG = Object.freeze({
	BLOCK_SIZE: 1,
	TEXTURE_PIXELS_PER_FACE: 16,
	CHUNK_SIZE_X: 16,
	CHUNK_SIZE_Y: 16,
	CHUNK_SIZE_Z: 16,
	STARTER_CHUNK_RADIUS: 2,
	TERRAIN_BASE_HEIGHT: 9,
	TERRAIN_HEIGHT_AMPLITUDE: 5,
	TERRAIN_MIN_HEIGHT: 5,
	TERRAIN_MAX_HEIGHT: 14,
	DIRT_DEPTH: 3,
	TRANSITION_DEPTH: 2,
	SEED: 133742
});

export const PLAYER_CONFIG = Object.freeze({
	HEIGHT: 1.8,
	WIDTH: 0.6,
	EYE_LEVEL: 1.62,
	SNEAK_HEIGHT: 1.5,
	SNEAK_EYE_LEVEL: 1.27,
	WALK_SPEED: 4.317,
	SPRINT_SPEED: 5.612,
	SNEAK_SPEED: 1.85,
	MAX_REACH: 4.5,
	GRAVITY: 24,
	JUMP_VELOCITY: 7.5,
	DOUBLE_TAP_SPRINT_WINDOW_MS: 300
});

export const HEALTH_CONFIG = Object.freeze({
	MAX_HEALTH: 20,
	HEARTS: 10,
	VOID_DAMAGE_START_Y: -6,
	VOID_TICK_SECONDS: 0.5,
	VOID_FIRST_DAMAGE: 2.5,
	VOID_DAMAGE_STEP: 0.5,
	SUFFOCATION_TICK_SECONDS: 0.5,
	SUFFOCATION_DAMAGE: 1
});

export const DAYLIGHT_CONFIG = Object.freeze({
	CYCLE_SECONDS: 3600,
	DAY_SECONDS: 2400,
	NIGHT_SECONDS: 1200,
	START_TIME_SECONDS: 600,
	SKY_RADIUS: 110,
	CELESTIAL_SIZE: 12,
	SUN_MAX_INTENSITY: 1.05,
	MOON_MAX_INTENSITY: 0.24,
	AMBIENT_DAY_INTENSITY: 0.42,
	AMBIENT_NIGHT_INTENSITY: 0.08
});

export const RENDER_CONFIG = Object.freeze({
	CLEAR_COLOR: [0.42, 0.72, 0.96, 1],
	FOG_COLOR: [0.53, 0.77, 0.95],
	FOG_DENSITY: 0.004,
	CAMERA_FOV: 1.18,
	CAMERA_MIN_Z: 0.03
});
